project_id = "ecrxtqvkncbbolmfqpxx"

[functions.parse-resume]
verify_jwt = true

[functions.generate-feedback]
verify_jwt = true

[functions.llama-chat]
verify_jwt = true

[functions.generate-summaries]
verify_jwt = true