// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecrxtqvkncbbolmfqpxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcnh0cXZrbmNiYm9sbWZxcHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTIyMjgsImV4cCI6MjA3NDAyODIyOH0.SaO0ElPkgsVooihdi53L6C4I9gSzRhrPsmD_E04E3tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});